### PR TITLE
fix buffer and integer edge cases

### PR DESCRIPTION
**Pull request by zignig**

### CODE REVIEW

**Comment by zignig** [comment]
Whoops ! , found some logic errors and a fence post. Fixed.

**Comment by zignig** [comment]
pls don't merge , error found.

**Comment by zignig** [comment]
should be go to go.

**Comment by zignig** [comment]
You do not seem to be interested in this anymore. 

Would you transfer this lib to me for updates ?

**Comment by almindor** [comment]
Hmm somehow I missed the good to go comment. Thanks for the fix. I'll give you write access for the time being.

**Pull request merged**
